name: James Rian
favicon: null
layout_spectrum: 0.7269666835200042
typography_spectrum: 0.2916776479687542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.041714149760082364
  lightness: 0.9721874219831079
  saturation: 0.4750631684437394
  rhythmicContrast: 0.45285163586959243
purpose: []
